#!/usr/bin/env bash
#
# Pre build hook for Docker Automated Build.
#

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

echo "🔵 pre_build"
source hooks/.config

echo "ℹ️ Inserting app version \"${APP_VERSION}\" in Dockerfile..."
sed -i "s/org.label-schema.version=\"unknown\"/org.label-schema.version=\"$APP_VERSION\"/" Dockerfile

echo "ℹ️ Register qemu-*-static for all supported processors except current"
echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"

docker run --rm --privileged multiarch/qemu-user-static:register --reset

echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
echo "✅ pre_build hook terminated successfully."