#!/usr/bin/env bash
#
# Push hook for Docker Automated Build.
#

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

echo "🔵 push"
source hooks/.config

# 1. push all images
IMAGE_NAME="${DOCKER_REPO//index.docker.io\/}"

for tag in ${docker_tags[@]}; do
  if [ ${tag} != ${DOCKER_TAG} ]; then
    for arch in ${verified_build_architectures[@]}; do
      echo "ℹ️ Tagging ${IMAGE_NAME}:${DOCKER_TAG}-${arch} with ${tag}-${arch}"
      echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
      echo
      docker tag ${IMAGE_NAME}:${DOCKER_TAG}-${arch} ${IMAGE_NAME}:${tag}-${arch}
    done
  fi
done

echo "ℹ️ Pushing all tags for ${IMAGE_NAME}"
echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
echo
docker push --all-tags ${IMAGE_NAME}
docker image ls

# 2. build and push manifest
for tag in ${docker_tags[@]}; do
  manifests=""

  for arch in ${verified_build_architectures[@]}; do
    manifests="${manifests} ${IMAGE_NAME}:${tag}-${arch}"
  done

  echo "ℹ️ Creating manifest ${IMAGE_NAME}:${tag}"
  echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
  docker manifest create ${IMAGE_NAME}:${tag} \
                              $manifests
  echo

  echo "ℹ️ Annotating manifest"
  echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
  for arch in ${verified_build_architectures[@]}; do
      docker manifest annotate ${IMAGE_NAME}:${tag} \
      ${IMAGE_NAME}:${tag}-${arch} \
      --os linux \
      --arch ${docker_to_manifest_map[${arch}]}
  done

  echo "ℹ️ Inspecting manifest ${IMAGE_NAME}:${tag}-${arch}"
  echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
  docker manifest inspect ${IMAGE_NAME}:${tag}-${arch}
  echo

  echo "ℹ️ Pushing manifest ${IMAGE_NAME}:${tag}"
  echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
  docker manifest push --purge "${IMAGE_NAME}:${tag}"
  echo
done

echo "⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
echo "✅ push hook terminated successfully."
