#!/command/with-contenv bash

cd /games || exit 1

UMASK=${UMASK:-022}
umask "$UMASK"

echo "Using port: ${PS3NETSRV_PORT}"
echo "Using whitelist: ${PS3NETSRV_WHITELIST}"

s6-setuidgid ps3netsrv /usr/local/bin/ps3netsrv /games "${PS3NETSRV_PORT}" ${PS3NETSRV_WHITELIST}
