#!/command/with-contenv bash

USER_ID=${USER_ID:-1000}
GROUP_ID=${GROUP_ID:-1000}

groupmod -o -g "$GROUP_ID" ps3netsrv
usermod -o -u "$USER_ID" ps3netsrv

echo '
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u ps3netsrv)
User gid:    $(id -g ps3netsrv)
-------------------------------------
"
