name: Update edge image
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          ref: main
      - name: Fetch release version
        id: fetch-release
        run: |
          PS3NETSRV_VERSION=$(curl -sL https://api.github.com/repos/aldostools/ps3netsrv/releases/latest | \
                              jq -r '.tag_name // empty')
          if [ -n "$PS3NETSRV_VERSION" ]; then
            echo "Found ps3netsrv release $PS3NETSRV_VERSION"

            # replacing APP_VERSION in .github/workflows/docker-publish.yml
            sed -ri "s/^(\s*)APP_VERSION\s*:\s*.*$/\1APP_VERSION: \"$PS3NETSRV_VERSION\"/" .github/workflows/docker-publish.yml
            echo "Updated APP_VERSION with $PS3NETSRV_VERSION in .github/workflows/docker-publish.yml"

            # replacing PS3NETSRV_VERSION in Dockerfile
            sed -ri "s/^(ARG PS3NETSRV_VERSION=).+$/\1$PS3NETSRV_VERSION/" Dockerfile
            echo "Updated PS3NETSRV_VERSION with $PS3NETSRV_VERSION in Dockerfile"

            echo "version=$PS3NETSRV_VERSION" >> $GITHUB_OUTPUT
          else
            echo "Could not determine the latest ps3netsrv release..."
            exit 1
          fi
      - name: Check for modified files
        id: git-check
        run: echo "modified=$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")" >> $GITHUB_OUTPUT
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "chore: update ps3netsrv to ${{ steps.fetch-release.outputs.version }}"
          git push
